import type { AnalysisReport, CategoryId, FlagNote } from "./types";

function f(title: string, detail: string): FlagNote {
  return { title, detail };
}

const DEMOS: Record<CategoryId, Omit<AnalysisReport, "createdAt" | "photoCount" | "isDemo" | "engine">> = {
  obuwie: {
    itemName: "Air Jordan 1 Retro High 'Chicago'",
    brand: "Nike",
    model: "Air Jordan 1 High",
    legitScore: 92,
    verdict: "LEGIT",
    confidenceNote: "Wysoka pewność na punktach kontrolnych. Bez ostrego kadru metki z kodem daty nie domykamy 100%.",
    conditionScore: 8.8,
    conditionLabel: "Very Good",
    conditionDetails: [
      "Cholewka ze skóry z naturalnym ziarnem, bez pęknięć na zgięciach",
      "Podeszwa elastyczna, bieżnik czytelny, bez odklejeń",
      "Szwy równe, bez pętli i odprutych nitek",
      "Wnętrze czyste, lekko zarysowana wkładka od noszenia",
      "Brak wieka pudełka i zapasowych sznurówek obniża komplet",
    ],
    accessories: "Pudełko bez wieka, brak zapasowych sznurówek",
    retailPricePln: 750,
    marketMinPln: 1450,
    marketMaxPln: 1700,
    replicaCostPln: 350,
    valuationSource: "live",
    valuationNote: "Widełki z aktywnych ofert Vinted, Amazon i StockX. Repliki tej kolorówki krążą znacznie taniej.",
    greenFlags: [
      f("Wzór szwów", "Ścieg i odległość od krawędzi zgodne z retailingiem Chicago"),
      f("Ziarno skóry", "Naturalne, nierównomierne — nie wygląda na korygowaną skórę replik"),
      f("Kształt pięty", "Proporcje Foxing i skrzydła typowe dla AJ1 High"),
    ],
    redFlags: [
      f("Kod daty", "Brak ostrego ujęcia metki na języku — pewność nie dochodzi do 100%"),
      f("Komplet", "Pudełko bez wieka obniża cenę o 50–80 zł względem full set"),
    ],
    checks: [
      { label: "Proporcje cholewki i skrzydeł", ok: true },
      { label: "Bieżnik i foxing", ok: true },
      { label: "Metka język / kod daty", ok: false },
      { label: "Komplet pudełka", ok: false },
    ],
    identificationNotes:
      "Kolorówka Chicago: biała cholewka, czerwone overlays, czarne skrzydła i Swoosh. Na rynku wtórnym 2024–26 para w Very Good bez full seta schodzi w widełkach 1450–1700 zł. Repliki tej serii mają twardszą skórę i płytszy tłoczony Nike Air.",
    missingShots: [
      {
        id: "tongue",
        label: "Metka wewnętrzna z kodem daty",
        reason: "Bez ostrego kadru metki nie domykamy pewności do 100%.",
      },
    ],
    searchQuery: "Air Jordan 1 Retro High Chicago",
    reportId: "LC-109345-PL",
    categoryId: "obuwie",
  },
  odziez: {
    itemName: "Stone Island Overshirt Cotton Canvas",
    brand: "Stone Island",
    model: "Overshirt Cotton Canvas",
    legitScore: 78,
    verdict: "LIKELY_LEGIT",
    confidenceNote: "Naszywka i wash tag wyglądają poprawnie. Brak zbliżenia spodu kompasu obniża pewność.",
    conditionScore: 8.2,
    conditionLabel: "Good",
    conditionDetails: [
      "Canvas bez przetarć na łokciach i kołnierzu",
      "Kolor równy, bez wyblaknięć na ramionach",
      "Guziki kompletne, nitowanie trzyma",
      "Lekkie mechacenie wewnątrz przy karku — noszenie, nie wada produkcyjna",
    ],
    accessories: "Oryginalna metka pielęgnacyjna",
    retailPricePln: 1890,
    marketMinPln: 720,
    marketMaxPln: 980,
    replicaCostPln: 220,
    valuationSource: "historical",
    valuationNote: "Mało aktywnych ofert — widełki z ostatnich sprzedaży na Vinted, OLX i Grailed.",
    greenFlags: [
      f("Overlock", "Ścieg wewnętrzny równy, typowy dla SI"),
      f("Wash tag", "Krój napisu i kody pielęgnacji zgodne z serią"),
    ],
    redFlags: [f("Kompas", "Brak ostrego kadru spodu badge'a — to kluczowy test SI")],
    checks: [
      { label: "Wash tag / skład", ok: true },
      { label: "Szwy wewnętrzne", ok: true },
      { label: "Spód naszywki kompas", ok: false },
    ],
    identificationNotes:
      "Overshirt Cotton Canvas Stone Island. Na rynku lumpeksowym SI schodzi szybko, jeśli kompas i tagi są kompletne. Bez zdjęcia spodu badge'a nie stawiamy LEGIT.",
    missingShots: [{ id: "logo", label: "Naszywka kompas", reason: "Potrzebne zbliżenie spodu badge'a." }],
    searchQuery: "Stone Island overshirt cotton canvas",
    reportId: "LC-204881-PL",
    categoryId: "odziez",
  },
  czapki: {
    itemName: "New Era 59FIFTY Yankees",
    brand: "New Era",
    model: "59FIFTY NY Yankees",
    legitScore: 88,
    verdict: "LEGIT",
    confidenceNote: "Haft i hologram spójne z retailingiem tej serii.",
    conditionScore: 9.0,
    conditionLabel: "Excellent",
    conditionDetails: [
      "Daszek prosty, bez załamań",
      "Haft gęsty, bez luźnych nitek",
      "Potnik czysty",
      "Zapięcie z tyłu lekko przetarte — kosmetyka",
    ],
    accessories: "Naklejka holograficzna na daszku",
    retailPricePln: 189,
    marketMinPln: 90,
    marketMaxPln: 140,
    replicaCostPln: 45,
    valuationSource: "live",
    valuationNote: "Aktywne oferty Vinted, OLX i Amazon w podobnym stanie.",
    greenFlags: [
      f("Haft z przodu", "Gęstość i wypełnienie logo NY zgodne z 59FIFTY"),
      f("Hologram", "Naklejka czytelna, bez rozwarstwienia"),
    ],
    redFlags: [f("Zapięcie", "Lekko porysowane — stan, nie autentyczność")],
    checks: [
      { label: "Haft i proporcje logo", ok: true },
      { label: "Hologram daszka", ok: true },
      { label: "Taśmy wewnętrzne", ok: true },
    ],
    identificationNotes:
      "New Era 59FIFTY NY Yankees, fitted. Na lumpeksie warto zestawić rozmiar z potnikiem — repliki często mają krzywy haft i słaby hologram.",
    missingShots: [],
    searchQuery: "New Era 59FIFTY Yankees",
    reportId: "LC-331002-PL",
    categoryId: "czapki",
  },
  akcesoria: {
    itemName: "Louis Vuitton Multiple Wallet",
    brand: "Louis Vuitton",
    model: "Multiple Wallet",
    legitScore: 54,
    verdict: "UNCERTAIN",
    confidenceNote: "Heat stamp jest miękki. Bez numeru seryjnego nie zamykamy werdyktu.",
    conditionScore: 7.4,
    conditionLabel: "Used",
    conditionDetails: [
      "Monogram równy, bez rozjechania na krawędziach",
      "Narożniki przetarte — typowe zużycie portfela",
      "Wnętrze czyste, bez plam",
      "Heat stamp płytki, SN nieczytelny na obecnym kadrze",
    ],
    accessories: "Brak pudełka i dust baga",
    retailPricePln: 3450,
    marketMinPln: 1600,
    marketMaxPln: 2200,
    replicaCostPln: 280,
    valuationSource: "estimate",
    valuationNote: "Szacunek przy braku kompletnych zdjęć numeru. Amazon i eBay pokazują analogiczne Multiple w 1600–2200 zł gdy SN jest czytelny.",
    greenFlags: [f("Monogram", "Układ i skala kwiatów równe")],
    redFlags: [
      f("Heat stamp", "Odcisk płytki, jak na wielu replikach"),
      f("Numer seryjny", "Brak ostrego kadru SN"),
    ],
    checks: [
      { label: "Wzór monogramu", ok: true },
      { label: "Heat stamp / SN", ok: false },
      { label: "Okucia", ok: true },
    ],
    identificationNotes:
      "Portfel Multiple LV. Na lumpeksie i OLX to jedna z najczęściej podrabianych sylwetek. Bez SN nie wystawiaj jako autentyk — lepiej ogłosić jako „do weryfikacji” albo dociągnąć zdjęcie stampu.",
    missingShots: [{ id: "stamp", label: "Heat stamp / SN", reason: "Numer seryjny musi być ostry i w całości." }],
    searchQuery: "Louis Vuitton Multiple Wallet",
    reportId: "LC-441229-PL",
    categoryId: "akcesoria",
  },
  zegarki: {
    itemName: "Rolex Submariner 16610",
    brand: "Rolex",
    model: "Submariner 16610",
    legitScore: 41,
    verdict: "LIKELY_FAKE",
    confidenceNote: "Koronka i czcionka na tarczy odbiegają od referencji. Serwis Rolex rozstrzyga, nie ten raport.",
    conditionScore: 8.0,
    conditionLabel: "Good",
    conditionDetails: [
      "Koperta bez głębokich uderzeń",
      "Bransoleta z równym luzem ogniw",
      "Szkło czyste",
      "Koronka nie spasowuje się z ramieniem jak w referencji 16610",
    ],
    accessories: "Brak pudełka i kart gwarancyjnych",
    retailPricePln: 0,
    marketMinPln: 32000,
    marketMaxPln: 42000,
    replicaCostPln: 1800,
    valuationSource: "historical",
    valuationNote: "Rynek wtórny 16610. Przy podejrzeniu repliki wartość spada do kosztu podróbki, nie do ceny Rolex.",
    greenFlags: [f("Proporcje koperty", "Średnica i lug width z grubsza zachowane")],
    redFlags: [
      f("Koronka", "Brak oczekiwanego spasowania z kopertą"),
      f("Tarcza", "Indeksy nierówne względem minutnika"),
    ],
    checks: [
      { label: "Cyferblat / indeksy", ok: false },
      { label: "Koronka", ok: false },
      { label: "Dekiel / grawer", ok: false },
    ],
    identificationNotes:
      "Submariner 16610 to częsty „lumpeksowy Rolex”. Nie wystawiaj jako oryginał. Jeśli chcesz sprzedać — opisuj jako zegarek w stylu, albo idź do serwisu. Amazon i eBay pełne są analogicznych listingów z banem za „Rolex”.",
    missingShots: [{ id: "back", label: "Dekiel", reason: "Grawer i szkło od tyłu są kluczowe." }],
    searchQuery: "Rolex Submariner 16610",
    reportId: "LC-550018-PL",
    categoryId: "zegarki",
  },
  elektronika: {
    itemName: "Apple AirPods Pro (2. gen)",
    brand: "Apple",
    model: "AirPods Pro 2",
    legitScore: 69,
    verdict: "UNCERTAIN",
    confidenceNote: "Spasowanie etui wygląda dobrze, ale SN nie jest czytelny.",
    conditionScore: 8.5,
    conditionLabel: "Very Good",
    conditionDetails: [
      "Etui bez pęknięć zawiasu",
      "Szczeliny równe",
      "Końcówki kompletne",
      "Tabliczka SN nieostra na zdjęciu",
    ],
    accessories: "Etui ładujące, brak pudełka",
    retailPricePln: 1299,
    marketMinPln: 620,
    marketMaxPln: 790,
    replicaCostPln: 160,
    valuationSource: "live",
    valuationNote: "Ceny z OLX, Vinted i Amazon dla używanych Pro 2 bez pudełka.",
    greenFlags: [f("Spasowanie etui", "Szczeliny i zawias równe")],
    redFlags: [f("Numer seryjny", "Tabliczka nieostra — nie da się zestawić z checkcoverage")],
    checks: [
      { label: "Spasowanie obudowy", ok: true },
      { label: "SN / checkcoverage", ok: false },
      { label: "Pudełko", ok: false },
    ],
    identificationNotes:
      "AirPods Pro 2. Na lumpeksie i OLX repliki są masowe. Zanim wystawisz — zeskanuj SN w checkcoverage.apple.com. Bez SN nie obiecuj oryginału w tytule ogłoszenia.",
    missingShots: [{ id: "plate", label: "Tabliczka / SN", reason: "Numer trzeba zestawić z checkcoverage Apple." }],
    searchQuery: "AirPods Pro 2",
    reportId: "LC-662441-PL",
    categoryId: "elektronika",
  },
  bizuteria: {
    itemName: "Pandora Moments Snake Chain",
    brand: "Pandora",
    model: "Moments Snake Chain",
    legitScore: 86,
    verdict: "LEGIT",
    confidenceNote: "Punca S925 i logo na zapięciu zgodne z serią Moments.",
    conditionScore: 8.1,
    conditionLabel: "Good",
    conditionDetails: [
      "Ogniwa bez pęknięć",
      "Lekkie zarysowania od noszenia",
      "Zapięcie sprężynuje",
      "Punca czytelna",
    ],
    accessories: "Brak pudełka",
    retailPricePln: 349,
    marketMinPln: 120,
    marketMaxPln: 180,
    replicaCostPln: 40,
    valuationSource: "live",
    valuationNote: "Aktywne oferty Vinted i Amazon w podobnym stanie.",
    greenFlags: [
      f("Punca S925", "Odcisk czytelny, głębokość typowa"),
      f("Zapięcie", "Logo Pandora i mechanizm zgodne z Moments"),
    ],
    redFlags: [f("Zużycie", "Lekkie zarysowania ogniw — stan, nie autentyczność")],
    checks: [
      { label: "Punca / próba", ok: true },
      { label: "Grawer marki", ok: true },
      { label: "Zapięcie", ok: true },
    ],
    identificationNotes:
      "Bransoletka Pandora Moments Snake Chain, srebro 925. W lumpeksie częsta i łatwa do zbycia na Vinted w 120–180 zł bez pudełka.",
    missingShots: [],
    searchQuery: "Pandora Moments bransoletka",
    reportId: "LC-778120-PL",
    categoryId: "bizuteria",
  },
  torebki: {
    itemName: "Michael Kors Hamilton — vintage",
    brand: "Michael Kors",
    model: "Hamilton",
    legitScore: 84,
    verdict: "LIKELY_LEGIT",
    confidenceNote: "Grawer kłódki, tłoczenie wewnątrz i okucia trzymają standard MK z wczesnych lat 2010. Brak ostrego date code'u na metce.",
    conditionScore: 7.0,
    conditionLabel: "Dobry+",
    conditionDetails: [
      "Skóra naturalna zmiękczona, z widocznymi zagnieceniami z użytkowania",
      "Drobne przetarcia i zmatowienia na brzegach uchwytów i paska",
      "Okucia w kolorze antycznego mosiądzu z powierzchniowymi mikrorysami",
      "Wszystkie ćwieki i nity kompletne i stabilnie osadzone",
      "Czysta podszewka wewnętrzna bez widocznych rozdarć",
    ],
    accessories: "Kłódka i pasek, brak dust baga",
    retailPricePln: 1890,
    marketMinPln: 280,
    marketMaxPln: 420,
    replicaCostPln: 90,
    valuationSource: "live",
    valuationNote: "Vintage Hamilton na Vinted/OLX w stanie Dobry+ schodzi w 280–420 zł. Amazon pokazuje nowsze Hamilton drożej — nie mieszaj z nowym detalem.",
    greenFlags: [
      f("Prawidłowy grawer kłódki", "Czyste, proporcjonalne liternictwo logo MK i napisu MICHAEL KORS na froncie kłódki"),
      f("Oryginalna podszewka vintage", "Deseń MK w okręgach odpowiada wzornictwu marki z wczesnych lat 2010"),
      f("Poprawne tłoczenie wewnątrz", "Krój pisma i głębokość tłoczenia na skórzanej wstawce zgodne ze standardem MK"),
      f("Solidne okucia", "Masywny łańcuch oraz prawidłowe mocowania uszu torebki"),
    ],
    redFlags: [
      f("Metka / date code", "Brak ostrego kadru metki wewnętrznej — do dociągnięcia przed wystawieniem"),
      f("Ślady użytkowania", "Zagniecenia i mikrorysy okuć: stan, nie fałszerstwo"),
    ],
    checks: [
      { label: "Grawer kłódki i logo", ok: true },
      { label: "Podszewka / deseń MK", ok: true },
      { label: "Tłoczenie wewnętrzne", ok: true },
      { label: "Metka z kodem daty", ok: false },
    ],
    identificationNotes:
      "Torebka Michael Kors Hamilton, linia vintage z wczesnych lat 2010. Na lumpeksie to częsty, dobrze zbywalny model: kłódka, łańcuch, skóra i podszewka w okręgach. Wystawiaj jako używaną Hamilton, nie jako nowy detal. Cena szybka ~280 zł, cierpliwa do ~420 zł.",
    missingShots: [
      {
        id: "tag",
        label: "Metka wewnętrzna z kodem daty",
        reason: "Bez ostrego kadru metki nie domykamy pewności do 100%.",
      },
    ],
    searchQuery: "Michael Kors Hamilton vintage",
    reportId: "LC-889300-PL",
    categoryId: "torebki",
  },
};

export function buildDemoReport(
  categoryId: CategoryId,
  photoCount: number,
  extra?: Partial<Pick<AnalysisReport, "itemName" | "searchQuery" | "sourceUrl" | "identificationNotes" | "valuationNote">>,
): AnalysisReport {
  const base = DEMOS[categoryId] ?? DEMOS.obuwie;
  return {
    ...base,
    ...extra,
    itemName: extra?.itemName || base.itemName,
    searchQuery: extra?.searchQuery || base.searchQuery,
    sourceUrl: extra?.sourceUrl,
    identificationNotes: extra?.identificationNotes
      ? `${extra.identificationNotes}\n\n${base.identificationNotes}`
      : base.identificationNotes,
    valuationNote: extra?.valuationNote ? `${extra.valuationNote} ${base.valuationNote}` : base.valuationNote,
    createdAt: new Date().toISOString(),
    photoCount,
    isDemo: true,
    engine: "demo",
    reportId: `LC-DEMO-${Date.now().toString(36).toUpperCase()}-PL`,
  };
}
